# Generated by Django 6.1 on 2026-08-20 08:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True)),
                ('mood', models.CharField(choices=[('happy', '😊 Happy'), ('calm', '😌 Calm'), ('productive', '⚡ Productive'), ('tired', '😴 Tired'), ('sad', '😢 Sad')], max_length=20)),
                ('note', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
