# Generated by Django 6.1 on 2026-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_moodlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='color_emoji',
            field=models.CharField(default='🟢', max_length=10),
        ),
    ]
