# Generated by Django 6.1 on 2026-08-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_todo_color_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
