# Generated by Django 6.1 on 2026-08-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_todo_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='reminder',
        ),
    ]
