# Generated by Django 6.1 on 2026-08-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_remove_todo_reminder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='color_emoji',
        ),
        migrations.AddField(
            model_name='todo',
            name='due_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='labels',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
