# Generated by Django 6.1 on 2026-08-21 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0006_remove_todo_color_emoji_todo_due_time_todo_labels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('attendees', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
